name: ui_actionable_bloc
description: A mixin on Bloc that allows to perform UI actions and get results back.
version: 0.0.3
homepage: https://github.com/nivisi/ui_actionable_bloc
repository: https://github.com/nivisi/ui_actionable_bloc
issue_tracker: https://github.com/nivisi/ui_actionable_bloc/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  nested:
  flutter_bloc:

dev_dependencies:
  monstarlab_lints:
